version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true # React のホットリロードをサポートするための設定
    depends_on:
      backend:
        condition: service_started

  backend:
    build: ./backend
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    volumes:
      - './db/init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5

volumes:
  db-data:
